### ISSUE TITLE
Erik changelog 0.1.17-49

### ISSUE THREAD

**Issue by SchSascha** [JULIELab/gepi#79]
- [ ] #40 (automated index updates)
- [x] #70 (resource versioning)
- [x] #73 (extract Neo4j concept project)
- [x] #83 (outline a solution for #73)
